pause deletion

diff --git a/.github/workflows/push-to-google-cloud-run-embedded-me.yml b/.github/workflows/push-to-google-cloud-run-embedded-me.yml
--- a/.github/workflows/push-to-google-cloud-run-embedded-me.yml
+++ b/.github/workflows/push-to-google-cloud-run-embedded-me.yml
@@ -81,16 +81,16 @@ jobs:
             --set-env-vars AQUA_TOKEN=${{ secrets.AQUA_TOKEN }} \
             --set-env-vars AQUA_SERVER=${{ secrets.AQUA_SERVER }} 
 
-      - name: Test container endpoints in cloud
-        run: |
-            sleep 5 # Give it some time to start up
-            url=$(gcloud run services describe $SERVICE_NAME --region=us-central1 --format="value(status.address.url)")
-            echo "Testing $url"
-            curl -X POST --fail $url/generate_traffic || { echo 'generate_traffic test failed'; exit 1; }
-            curl -X POST --fail $url/deploy_malware || { echo 'deploy_malware test failed'; exit 1; }
-            curl -X POST --fail $url/deploy_nmap || { echo 'deploy_nmap test failed'; exit 1; }
-            curl -X POST --fail $url/read_passwords || { echo 'read_passwords test failed'; exit 1; }     
+      # - name: Test container endpoints in cloud
+      #   run: |
+      #       sleep 5 # Give it some time to start up
+      #       url=$(gcloud run services describe $SERVICE_NAME --region=us-central1 --format="value(status.address.url)")
+      #       echo "Testing $url"
+      #       curl -X POST --fail $url/generate_traffic || { echo 'generate_traffic test failed'; exit 1; }
+      #       curl -X POST --fail $url/deploy_malware || { echo 'deploy_malware test failed'; exit 1; }
+      #       curl -X POST --fail $url/deploy_nmap || { echo 'deploy_nmap test failed'; exit 1; }
+      #       curl -X POST --fail $url/read_passwords || { echo 'read_passwords test failed'; exit 1; }     
 
-      - name: Remove Service from Cloud Run
-        run: |
-            gcloud run services delete $SERVICE_NAME --region=$GCP_REGION --quiet
+      # - name: Remove Service from Cloud Run
+      #   run: |
+      #       gcloud run services delete $SERVICE_NAME --region=$GCP_REGION --quiet
